networks:
  mynetwork:
    driver: bridge
services:
  bitcoind:
    restart: always
    networks:
      - mynetwork
    build:
      context: ./bitcoind
      args:
        BUILD_BITCOINCORE_VERSION: ${BUILD_BITCOINCORE_VERSION}
        BUILD_BITCOIN_CORE_SIGNATURE: ${BUILD_BITCOIN_CORE_SIGNATURE}
    working_dir: /home/user01
    user: user01
    volumes:
      - ${HOST_SERVER_DIR}/bitcoind:/home/user01/.bitcoin:rw
      - ./bitcoind/bitcoin.conf:/home/user01/.bitcoin/bitcoin.conf:rw
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        /opt/bitcoin/bin/bitcoind
  #         sleep 10000
  #         top
  #         /opt/bitcoin/bin/test_bitcoin --show_progress && top

  electrs:
    networks:
      - mynetwork
    build:
      context: ./electrs
      args:
        BUILD_ELECTRS_VERSION: ${BUILD_ELECTRS_VERSION}
    volumes:
      - ${HOST_SERVER_DIR}/bitcoind:/home/user01/.bitcoin
      - ${HOST_SERVER_DIR}/electrs-data:/home/user01/electrs-data
      - ./electrs/electrs-config.toml:/home/user01/electrs-config.toml
    healthcheck:
      timeout: 10s
    restart: always
    stdin_open: true
    tty: true
    working_dir: /home/user01/electrs-data
    command: >
      sh -c "electrs --conf /home/user01/electrs-config.toml"
    depends_on:
      - bitcoind

  nginx:
    networks:
      - mynetwork
    build:
      context: ./nginx
    # restart: always
    ports:
      - "50002:50002"
      - "50003:50003"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site-default:/etc/nginx/sites-enabled/default
      - ./nginx/electrs-reverse-proxy.conf:/etc/nginx/streams-enabled/electrs-reverse-proxy.conf
      - ./nginx/files-runtime:/home/user01/files-runtime
      - ./nginx/start.sh:/home/user01/start.sh
    #     - ./cert.crt:/nginx/cert.crt
    #      - ./cert.key:/nginx/cert.key
    command: sh -c "chmod +x /home/user01/start.sh && /home/user01/start.sh"

#  blockexplorer:
#  rdpserver:
#

# privacy-router:
#   container_name: internetrouter
#   build: 
#     context: .
#     dockerfile: Dockerfile-internetrouter
#   volumes:
#     - ./openvpn.conf:/data/.openvpn/openvpn.confg
