network = "bitcoin"
daemon_dir= "/home/user01/.bitcoin"
daemon_rpc_addr = "bitcoind:29123"
daemon_p2p_addr = "bitcoind:8333"

electrum_rpc_addr = "0.0.0.0:50001"
db_dir = "/home/user01/electrs-data/db"
index_lookup_limit = 1000

log_filters = "INFO"
timestamp = true
